# Generated by Django 5.1 on 2024-08-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("country", models.CharField(blank=True, max_length=200, null=True)),
                ("shipment", models.CharField(blank=True, max_length=200, null=True)),
                ("schedule_deliver_date", models.DateTimeField(blank=True, null=True)),
                ("deliver_to_client", models.DateTimeField(blank=True, null=True)),
                ("recorded_deliver_date", models.DateTimeField(blank=True, null=True)),
                (
                    "pack_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "manufacturing_site",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "freight_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
            ],
        ),
    ]
