# Generated by Django 5.1 on 2024-08-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="freight_cost",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="weight",
        ),
    ]
