# Generated by Django 5.1 on 2024-08-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_delivery_freight_cost_remove_delivery_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="name_id",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
